### ISSUE TITLE
The box "Customization package" in the diagram should be Nexus

### ISSUE THREAD

**Issue by xqwangatgit** [IBM/wc-devops-utilities#3]
The box "Customization package" in the diagram should be Nexus, just want to make it very clear.

**Comment by kongyi-ibm** [comment]
I want to keep the word "customization package".  The keep point is that when build docker image, it will fetch customization package. It is doesn't matter the package from where ( Nexus is one optional, but customer put the package on some remote repository, maybe apache server which can be access use http url, that is okay ).  So in diagram, we just want to mentioned the "customization package"
